[tool.poetry]
name = "kino"
version = "0.1.0"
description = "Honza Javorek's personal cinema scraper"
authors = ["Honza Javorek <mail@honzajavorek.cz>"]
license = "AGPL-3.0-only"
readme = "README.md"

[tool.poetry.scripts]
kino = "kino.__main__:main"

[tool.poetry.dependencies]
python = "^3.12"
crawlee = {extras = ["beautifulsoup"], version = "^0.6.10"}
click = "^8.2.1"
pydantic = "^2.11.7"
ics = "^0.7.2"
pycountry = "^24.6.1"
emoji-country-flag = "^2.0.1"

[tool.poetry.group.dev.dependencies]
pytest = "^8.4.0"
pytest-ruff = "^0.4.1"
ruff = "^0.11.13"

[tool.pytest.ini_options]
python_files = "test_*.py"
testpaths = "tests"
addopts = "--import-mode=importlib --ff --ruff --ruff-format"

[tool.ruff]
target-version = "py312"

[tool.ruff.lint]
extend-select = ["I"]

[tool.ruff.lint.isort]
combine-as-imports = true
lines-after-imports = 2

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
