name: scrape

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:  # allows running this workflow manually from the Actions tab

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:  # only one concurrent deployment
  group: pages
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Tests
        run: uv run pytest

      - name: Code
        run: uv run ruff check

      - name: Scrape
        run: uv run kino

      - name: Publish
        run: mkdir ./site && mv *.ics ./site/

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
